title: "Just. Image. It."
description: "A blog about microscopy, microscope hardware, image processing, and, occasionally, biology."
timezone: Europe/Berlin
url: https://aettinger.github.io/
sass:
    sass_dir: _sass
